### ISSUE TITLE
Client Edit

### ISSUE THREAD

**Issue by madeleineworrall** [PrimitiveSocial/Caprock-Cafe#1]
@jetercotton can you pls assign a dev to this?

Client would like to move the gift card section UP. See below: 
[gift card relocate (1).pdf](https://github.com/PrimitiveSocial/CaprockRestaurant-/files/3740230/gift.card.relocate.1.pdf)

Please let me know how long this will take - I dropped the ball on this last week but if we can get it done asap that would be amazing. 

Thanks team!

**Comment by jetercotton** [comment]
@matthewPrimitive Can you have a look at this, and let MADs know if you need any clarity, and provide me with a point estimate in order to determine a delivery date?

**Comment by matthewPrimitive** [comment]
@jetercotton if this can be done just throught the ftp code and not wordpress it will only take a second probably. So 1 point

**Comment by jetercotton** [comment]
@matthewPrimitive That's amazing. Can you have this done EOD? You would make @madeleineworrall a happy person if so.

**Comment by matthewPrimitive** [comment]
@jetercotton give me the creds and since im not on starbucks wifi i can get this done quick for @madeleineworrall

**Comment by jetercotton** [comment]
https://docs.google.com/document/d/1ZAQdGoCKRqrOsDklU1NYRQvMD3wWZS9XU6i40GMlwRM/edit

**Comment by matthewPrimitive** [comment]
@jetercotton you missed my message but thanks anyways

**Comment by matthewPrimitive** [comment]
@jetercotton looks like its thru wordpess. Can you give me the login for that

**Comment by madeleineworrall** [comment]
@matthewPrimitive thank goodness for your college dorm wifi

**Comment by jetercotton** [comment]
@matthewPrimitive The doc has been updated with the requested credentials.

**Comment by matthewPrimitive** [comment]
@jetercotton this is done @madeleineworrall

**Comment by madeleineworrall** [comment]
Can you drop the link pls @matthewPrimitive

**Comment by matthewPrimitive** [comment]
@madeleineworrall https://caprockcafe.com/merchandise/ this?

**Comment by madeleineworrall** [comment]
@matthewPrimitive the gift card section hasn't been moved...

**Comment by matthewPrimitive** [comment]
@madeleineworrall 
its at the top of the page right? did you do a refresH?
![Screen Shot 2019-10-17 at 2 48 35 PM](https://user-images.githubusercontent.com/50176006/67042360-52e27900-f0ed-11e9-8b5f-43af4ec7f7ca.png)

**Comment by jetercotton** [comment]
@matthewPrimitive I'm still seeing those fun ladies first on the page after a cache clear.
![image](https://user-images.githubusercontent.com/45576954/67042682-00558c80-f0ee-11e9-86ca-aa93678290f6.png)


Can you mash the "Clear Cache" button with the little tiger on it shown in your WP menu bar? I think the site itself could use a cache clear in this instance.

**Comment by madeleineworrall** [comment]
Awesome! Thank you!

**Comment by madeleineworrall** [comment]
There is nothing more cringy than those photos

**Comment by matthewPrimitive** [comment]
IDK what your talking about they are the best photos ive seen

**Comment by madeleineworrall** [comment]
Did we get this figured out?

**Comment by madeleineworrall** [comment]
We need to swap out the link for the apply online CTA's changed to this:
[caprock current jobs.pdf](https://github.com/PrimitiveSocial/Caprock-Cafe/files/3752142/caprock.current.jobs.pdf)

**Comment by jetercotton** [comment]
@madeleineworrall I'm moving this to a new issue so that we don't confuse the new task with the old task.
