### ISSUE TITLE
Update Apply Online Link

### ISSUE THREAD

**Issue by jetercotton** [PrimitiveSocial/Caprock-Cafe#2]
We need to swap out the link for the apply online CTA's changed to this:
caprock current jobs.pdf

**Due: Thursday EOD**

**Comment by matthewPrimitive** [comment]
@jetercotton You didnt link me to the pdf, you just put the name of the pdf

**Comment by jetercotton** [comment]
[caprock.current.jobs.pdf](https://github.com/PrimitiveSocial/Caprock-Cafe/files/3764372/caprock.current.jobs.pdf)


@matthewPrimitive here you go big boy

**Comment by matthewPrimitive** [comment]
@jetercotton this should be all done.

**Comment by jetercotton** [comment]
approved.

**Comment by jetercotton** [comment]
@madeleineworrall Here's the instructional video to send to the client on how to update the PDFs. Below is also a bulleted list of the steps.

Video Tutorial: https://www.loom.com/share/ff86b52bd0ab4a66af54d25396d7c97b

-Ensure the new PDF being uploaded is labeled either "orlandos-current-jobs.pdf" or "caprock-current-jobs.pdf" depending on the site the PDf is being uploaded to.
-Navigate to the Media bin in the backend.
-Delete the old PDF.
-Upload the new PDF to the media bin.
